// Code generated by "sh shell.sh"; DO NOT EDIT.
package parser

import (
	"craftinginterpreters/lox/scanner"
)

type Visitor interface {
	VisitorBinary(*Binary) any
	VisitorGrouping(*Grouping) any
	VisitorLiteral(*Literal) any
	VisitorUnary(*Unary) any
}

type Expr interface {
	Accept(Visitor) any
}

type Binary struct {
	Left     Expr
	Operator scanner.Token
	Right    Expr
}

func (i *Binary) Accept(v Visitor) any {
	return v.VisitorBinary(i)
}

type Grouping struct {
	Expression Expr
}

func (i *Grouping) Accept(v Visitor) any {
	return v.VisitorGrouping(i)
}

type Literal struct {
	Value any
}

func (i *Literal) Accept(v Visitor) any {
	return v.VisitorLiteral(i)
}

type Unary struct {
	Operator scanner.Token
	Right    Expr
}

func (i *Unary) Accept(v Visitor) any {
	return v.VisitorUnary(i)
}
