// Code generated by "sh shell.sh"; DO NOT EDIT.
package parser

import (
	"craftinginterpreters/lox/scanner"
)

type ExprVisitor interface {
	VisitAssignExpr(*Assign) any
	VisitBinaryExpr(*Binary) any
	VisitGroupingExpr(*Grouping) any
	VisitLiteralExpr(*Literal) any
	VisitUnaryExpr(*Unary) any
	VisitVariableExpr(*Variable) any
}

type Expr interface {
	Accept(ExprVisitor) any
}

type Assign struct {
	Name  scanner.Token
	Value Expr
}

func (i *Assign) Accept(v ExprVisitor) any {
	return v.VisitAssignExpr(i)
}

type Binary struct {
	Left     Expr
	Operator scanner.Token
	Right    Expr
}

func (i *Binary) Accept(v ExprVisitor) any {
	return v.VisitBinaryExpr(i)
}

type Grouping struct {
	Expression Expr
}

func (i *Grouping) Accept(v ExprVisitor) any {
	return v.VisitGroupingExpr(i)
}

type Literal struct {
	Value any
}

func (i *Literal) Accept(v ExprVisitor) any {
	return v.VisitLiteralExpr(i)
}

type Unary struct {
	Operator scanner.Token
	Right    Expr
}

func (i *Unary) Accept(v ExprVisitor) any {
	return v.VisitUnaryExpr(i)
}

type Variable struct {
	Name scanner.Token
}

func (i *Variable) Accept(v ExprVisitor) any {
	return v.VisitVariableExpr(i)
}
