// Code generated by "sh shell.sh"; DO NOT EDIT.
package parser

import (
	"craftinginterpreters/lox/scanner"
)

type Visitor interface {
	VisitBinaryExpr(*Binary) any
	VisitGroupingExpr(*Grouping) any
	VisitLiteralExpr(*Literal) any
	VisitUnaryExpr(*Unary) any
}

type Expr interface {
	Accept(Visitor) any
}

type Binary struct {
	Left     Expr
	Operator scanner.Token
	Right    Expr
}

func (i *Binary) Accept(v Visitor) any {
	return v.VisitBinaryExpr(i)
}

type Grouping struct {
	Expression Expr
}

func (i *Grouping) Accept(v Visitor) any {
	return v.VisitGroupingExpr(i)
}

type Literal struct {
	Value any
}

func (i *Literal) Accept(v Visitor) any {
	return v.VisitLiteralExpr(i)
}

type Unary struct {
	Operator scanner.Token
	Right    Expr
}

func (i *Unary) Accept(v Visitor) any {
	return v.VisitUnaryExpr(i)
}
