// Code generated by "sh shell.sh"; DO NOT EDIT.
package parser

import (
	"craftinginterpreters/lox/scanner"
)

type StmtVisitor interface {
	VisitBlockStmt(*Block) any
	VisitExpressionStmt(*Expression) any
	VisitPrintStmt(*Print) any
	VisitVarStmt(*Var) any
}

type Stmt interface {
	Accept(StmtVisitor) any
}

type Block struct {
	Statements []Stmt
}

func (i *Block) Accept(v StmtVisitor) any {
	return v.VisitBlockStmt(i)
}

type Expression struct {
	Expression Expr
}

func (i *Expression) Accept(v StmtVisitor) any {
	return v.VisitExpressionStmt(i)
}

type Print struct {
	Expression Expr
}

func (i *Print) Accept(v StmtVisitor) any {
	return v.VisitPrintStmt(i)
}

type Var struct {
	Name        scanner.Token
	Initializer Expr
}

func (i *Var) Accept(v StmtVisitor) any {
	return v.VisitVarStmt(i)
}
